##
UNPACK:		../UNPACK/unpacker.xml
DIGIT:		../DIGIT/digit_data_e72_20260317.xml
CMAP:		../CMAP/channel_map_e72_20260313.xml
##
HDPRM:		../HDPRM/HodoParam_e72_20251113
#HDPRM:		../HDPRM/HodoParam_0
HDPHC:		../HDPHC/HodoPHCParam_0
USER:		../USER/UserParam_e72_online
DCGEO:		../DCGEO/DCGeomParam_e72_online
DSIZE:		../DSIZE/DetSize_e72_0
TPCPAD:		../TPCPAD/TpcPad_20210205
DCTDC:		../DCTDC/DCTdcParam_01928
DCDRFT:		../DCDRFT/DCDriftParam_01928.root
