UNPACK:	param/UNPACK/unpacker.xml
DIGIT:	param/DIGIT/digit_data_e72_20260317.xml
CMAP:	param/CMAP/channel_map_e72_20260402.xml
USER:	param/USER/UserParam_e72_20260403
HDPRM:	param/HDPRM/HodoParam_0
HDPHC:	param/HDPHC/HodoPHCParam_0

DCGEO:	param/DCGEO/DCGeomParam_run03773
DCTDC:	param/DCTDC/DCTdcParam_run03773
DCDRFT:	param/DCDRFT/DCDriftParam_run03773.root

TPCPRM:	param/TPCPRM/TPCParam_0
TPCPOS:	param/TPCPOS/TPCPositionCorrectionMap_0
FLDMAP:	param/FLDMAP/ShsFieldMap_20210526_Extrapolated
D5MTX:	param/TM/D5TransferMatrix.param
